### ISSUE TITLE
Auth issue.

### ISSUE THREAD

**Issue by MattMckenzy** [WardPearce/jellyfin-session-kicker#26]
I've tried several different ways to perform a GET request, making sure to include the Authorization header with the given basic token supplied at runtime, and I always received invalid auth. Here's an example of request and response:

root@63fa9d5d9c8b:/# curl jellyfin-session-kicker --header "Authorization: basic TJziSL1bx4X8fYLJZnlZHxyXOjvUgLdXXPGtbn7NyAgOsj4leJohXQ"
{"error": "Invalid basic auth credentials"}

I would greatly appreciate any help figuring this out! Or providing another means to whitelist would also work.

Thank you.

**Comment by WardPearce** [comment]
Afternoon Matt,
Session kicker uses [Basic auth](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#basic_authentication_scheme). This means you need to base64 encode a string like `base64.b64encode(f":{key}")`

Your key would be something like `OlRKemlTTDFieDRYOGZZTEpabmxaSHh5WE9qdlVnTGRYWFBHdGJuN055QWdPc2o0bGVKb2hYUQ==`

**Comment by MattMckenzy** [comment]
Thank you, I got it working!

One last quick question, is there a place I can see all of the possible media types? I'd like to completely whitelist some users.

Thanks you!

**Comment by WardPearce** [comment]
uuggh don't thinks so sorry, maybe the jellyfin api docs?
