### ISSUE TITLE
Env varible default bool bug and feature to accrue time by device rather than user

### ISSUE THREAD

**Issue by ShanaryS** [WardPearce/jellyfin-session-kicker#28]
os.getenv(A, B) looks for env variable A and returns B as a default if it doesn't exist. However variable B is always returned as a string, regardless of what the function was called with.

For DELETE_DEVICE_IF_NO_MEDIA_CONTROLS, B is set to the bool False, which gets converted to the string "False". This will always True for bool("False") since the string is not empty. This is a very annoying oversight from the python developers. A better check is:

DELETE_DEVICE_IF_NO_MEDIA_CONTROLS = os.getenv("DELETE_DEVICE_IF_NO_MEDIA_CONTROLS", "True").lower() == "true"

I've created a PR that includes this change. This PR also includes a new env variable that allows time to be accrued by DeviceId rather than UserId. So the same user with multiple devices is treated differently.

PR: https://github.com/WardPearce/jellyfin-session-kicker/pull/27

**Comment by WardPearce** [comment]
Will be deployed whenever https://github.com/WardPearce/jellyfin-session-kicker/pull/29 merges.

Haven't been active in this repo for a while, so appears some things will need to change

**Comment by WardPearce** [comment]
Thanks for the PR, merged into production now. Docker image should be up.
